import {
  POSE_LANDMARKS,
  POSE_LANDMARKS_LEFT,
  POSE_LANDMARKS_NEUTRAL,
  POSE_LANDMARKS_RIGHT,
} from "@mediapipe/pose"

const POSELANDMARKS_LEFT = POSE_LANDMARKS_LEFT || window.POSE_LANDMARKS_LEFT
const POSELANDMARKS_RIGHT = POSE_LANDMARKS_RIGHT || window.POSE_LANDMARKS_RIGHT
const POSELANDMARKS_NEUTRAL =
  POSE_LANDMARKS_NEUTRAL || window.POSE_LANDMARKS_NEUTRAL
const POSELANDMARKS = POSE_LANDMARKS

export const POSE_LANDMARKS_ALL = {
  ...POSELANDMARKS_LEFT,
  ...POSELANDMARKS_RIGHT,
  ...POSELANDMARKS_NEUTRAL,
  ...POSELANDMARKS,
}

export const POSE_CONNECTIONS = [
  [POSE_LANDMARKS_ALL.RIGHT_WRIST, POSE_LANDMARKS_ALL.RIGHT_ELBOW],
  [POSE_LANDMARKS_ALL.LEFT_WRIST, POSE_LANDMARKS_ALL.LEFT_ELBOW],
  [POSE_LANDMARKS_ALL.RIGHT_ELBOW, POSE_LANDMARKS_ALL.RIGHT_SHOULDER],
  [POSE_LANDMARKS_ALL.LEFT_ELBOW, POSE_LANDMARKS_ALL.LEFT_SHOULDER],
  [POSE_LANDMARKS_ALL.RIGHT_SHOULDER, POSE_LANDMARKS_ALL.LEFT_SHOULDER],
  [POSE_LANDMARKS_ALL.RIGHT_SHOULDER, POSE_LANDMARKS_ALL.RIGHT_HIP],
  [POSE_LANDMARKS_ALL.LEFT_SHOULDER, POSE_LANDMARKS_ALL.LEFT_HIP],
  [POSE_LANDMARKS_ALL.RIGHT_HIP, POSE_LANDMARKS_ALL.LEFT_HIP],
  [POSE_LANDMARKS_ALL.RIGHT_HIP, POSE_LANDMARKS_ALL.RIGHT_KNEE],
  [POSE_LANDMARKS_ALL.LEFT_HIP, POSE_LANDMARKS_ALL.LEFT_KNEE],
  [POSE_LANDMARKS_ALL.RIGHT_KNEE, POSE_LANDMARKS_ALL.RIGHT_ANKLE],
  [POSE_LANDMARKS_ALL.LEFT_KNEE, POSE_LANDMARKS_ALL.LEFT_ANKLE],
  [POSE_LANDMARKS_ALL.RIGHT_ANKLE, POSE_LANDMARKS_ALL.RIGHT_FOOT_INDEX],
  [POSE_LANDMARKS_ALL.LEFT_ANKLE, POSE_LANDMARKS_ALL.LEFT_FOOT_INDEX],
]

export const mapping = [
  [0],
  [1],
  [2],
  [3],
  [4, 5],
  [4, 6],
  [2],
  [3],
  [8],
  [9],
  [8],
  [9],
  [5, 7],
  [6, 7],
  [10],
  [11],
  [12],
  [13],
  [8],
  [9],
]

export const LANDMARK_MAPPING = [
  {
    center: POSE_LANDMARKS_ALL.RIGHT_ELBOW,
    start: POSE_LANDMARKS_ALL.RIGHT_SHOULDER,
    end: POSE_LANDMARKS_ALL.RIGHT_WRIST,
  },
  {
    center: POSE_LANDMARKS_ALL.LEFT_ELBOW,
    start: POSE_LANDMARKS_ALL.LEFT_SHOULDER,
    end: POSE_LANDMARKS_ALL.LEFT_WRIST,
  },
  {
    center: POSE_LANDMARKS_ALL.RIGHT_SHOULDER,
    start: POSE_LANDMARKS_ALL.RIGHT_ELBOW,
    end: POSE_LANDMARKS_ALL.RIGHT_HIP,
  },
  {
    center: POSE_LANDMARKS_ALL.LEFT_SHOULDER,
    start: POSE_LANDMARKS_ALL.LEFT_ELBOW,
    end: POSE_LANDMARKS_ALL.LEFT_HIP,
  },
  {
    center: POSE_LANDMARKS_ALL.RIGHT_SHOULDER,
    start: POSE_LANDMARKS_ALL.RIGHT_HIP,
    end: POSE_LANDMARKS_ALL.LEFT_SHOULDER,
  },
  {
    center: POSE_LANDMARKS_ALL.LEFT_SHOULDER,
    start: POSE_LANDMARKS_ALL.LEFT_HIP,
    end: POSE_LANDMARKS_ALL.RIGHT_SHOULDER,
  },
  {
    center: POSE_LANDMARKS_ALL.RIGHT_SHOULDER,
    start: POSE_LANDMARKS_ALL.RIGHT_ELBOW,
    end: POSE_LANDMARKS_ALL.LEFT_SHOULDER,
  },
  {
    center: POSE_LANDMARKS_ALL.LEFT_SHOULDER,
    start: POSE_LANDMARKS_ALL.LEFT_ELBOW,
    end: POSE_LANDMARKS_ALL.RIGHT_SHOULDER,
  },
  {
    center: POSE_LANDMARKS_ALL.RIGHT_HIP,
    start: POSE_LANDMARKS_ALL.RIGHT_SHOULDER,
    end: POSE_LANDMARKS_ALL.RIGHT_KNEE,
  },
  {
    center: POSE_LANDMARKS_ALL.LEFT_HIP,
    start: POSE_LANDMARKS_ALL.LEFT_SHOULDER,
    end: POSE_LANDMARKS_ALL.LEFT_KNEE,
  },
  {
    center: POSE_LANDMARKS_ALL.RIGHT_HIP,
    start: POSE_LANDMARKS_ALL.RIGHT_KNEE,
    end: POSE_LANDMARKS_ALL.LEFT_HIP,
  },
  {
    center: POSE_LANDMARKS_ALL.LEFT_HIP,
    start: POSE_LANDMARKS_ALL.LEFT_KNEE,
    end: POSE_LANDMARKS_ALL.RIGHT_HIP,
  },
  {
    center: POSE_LANDMARKS_ALL.RIGHT_HIP,
    start: POSE_LANDMARKS_ALL.RIGHT_SHOULDER,
    end: POSE_LANDMARKS_ALL.LEFT_HIP,
  },
  {
    center: POSE_LANDMARKS_ALL.LEFT_HIP,
    start: POSE_LANDMARKS_ALL.LEFT_SHOULDER,
    end: POSE_LANDMARKS_ALL.RIGHT_HIP,
  },

  {
    center: POSE_LANDMARKS_ALL.RIGHT_KNEE,
    start: POSE_LANDMARKS_ALL.RIGHT_HIP,
    end: POSE_LANDMARKS_ALL.RIGHT_ANKLE,
  },
  {
    center: POSE_LANDMARKS_ALL.LEFT_KNEE,
    start: POSE_LANDMARKS_ALL.LEFT_HIP,
    end: POSE_LANDMARKS_ALL.LEFT_ANKLE,
  },
  {
    center: POSE_LANDMARKS_ALL.RIGHT_ANKLE,
    start: POSE_LANDMARKS_ALL.RIGHT_KNEE,
    end: POSE_LANDMARKS_ALL.RIGHT_FOOT_INDEX,
  },
  {
    center: POSE_LANDMARKS_ALL.LEFT_ANKLE,
    start: POSE_LANDMARKS_ALL.LEFT_KNEE,
    end: POSE_LANDMARKS_ALL.LEFT_FOOT_INDEX,
  },
  {
    center: POSE_LANDMARKS_ALL.RIGHT_HIP,
    start: POSE_LANDMARKS_ALL.RIGHT_SHOULDER,
    end: POSE_LANDMARKS_ALL.RIGHT_KNEE,
  },
  {
    center: POSE_LANDMARKS_ALL.LEFT_HIP,
    start: POSE_LANDMARKS_ALL.LEFT_SHOULDER,
    end: POSE_LANDMARKS_ALL.LEFT_KNEE,
  },
]

export const TARGET_LMARK_MAPPING = [
  POSE_LANDMARKS_ALL.RIGHT_WRIST,
  POSE_LANDMARKS_ALL.LEFT_WRIST,
  POSE_LANDMARKS_ALL.RIGHT_ELBOW,
  POSE_LANDMARKS_ALL.LEFT_ELBOW,
  POSE_LANDMARKS_ALL.RIGHT_SHOULDER,
  POSE_LANDMARKS_ALL.LEFT_SHOULDER,
  POSE_LANDMARKS_ALL.RIGHT_HIP,
  POSE_LANDMARKS_ALL.LEFT_HIP,
  POSE_LANDMARKS_ALL.RIGHT_KNEE,
  POSE_LANDMARKS_ALL.LEFT_KNEE,
  POSE_LANDMARKS_ALL.RIGHT_ANKLE,
  POSE_LANDMARKS_ALL.LEFT_ANKLE,
  POSE_LANDMARKS_ALL.RIGHT_FOOT_INDEX,
  POSE_LANDMARKS_ALL.LEFT_FOOT_INDEX,
  POSE_LANDMARKS_ALL.RIGHT_HEEL,
  POSE_LANDMARKS_ALL.LEFT_HEEL,
  POSE_LANDMARKS_ALL.RIGHT_INDEX,
  POSE_LANDMARKS_ALL.LEF_INDEX,
  POSE_LANDMARKS_ALL.RIGHT_EYE,
  POSE_LANDMARKS_ALL.LEFT_EYE,
  POSE_LANDMARKS_ALL.RIGHT_EAR,
  POSE_LANDMARKS_ALL.LEFT_EAR,
  POSE_LANDMARKS_ALL.NOSE,
]
